name: TODO scan

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: TODO scanning
        uses: alstr/todo-to-issue-action@v5
